/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Player1 = string;
export type TeamName = string;
export type TeamAbbrev = string;
export type League = string;
export type Season = number;
export type Teams = TeamSeason[];
export type Player2 = string;
export type Team = string;
export type Player3 = string;
export type Rs = number;
export type Rs9 = number;
export type Ba = number;
export type Ab = number;
export type Ab9 = number;
export type H = number;
export type H9 = number;
export type Hr = number;
export type Hr9 = number;
export type Abhr = number;
export type So = number;
export type So9 = number;
export type Bb = number;
export type Bb9 = number;
export type Obp = number;
export type Rc = number;
export type Babip = number;
export type Ra = number;
export type Ra9 = number;
export type Oppba = number;
export type Oppab9 = number;
export type Opph = number;
export type Opph9 = number;
export type Opphr = number;
export type Opphr9 = number;
export type Oppabhr = number;
export type Oppk = number;
export type Oppk9 = number;
export type Oppbb = number;
export type Oppbb9 = number;
export type Whip = number;
export type Lob = number;
export type E = number;
export type Fip = number;
export type Rd = number;
export type Rd9 = number;
export type InningsPlayed = number;
export type InningsGame = number;
export type Wins = number;
export type Losses = number;
export type WinsByRunRule = number;
export type LossesByRunRule = number;
export type Seasons = number[];
export type SweepsW = number;
export type SweepsL = number;
export type Splits = number;
export type PlayerA = string;
export type PlayerZ = string;
export type Team1 = string;
export type Player4 = string;
export type Rs1 = number;
export type Rs91 = number;
export type Ba1 = number;
export type Ab1 = number;
export type Ab91 = number;
export type H1 = number;
export type H91 = number;
export type Hr1 = number;
export type Hr91 = number;
export type Abhr1 = number;
export type So1 = number;
export type So91 = number;
export type Bb1 = number;
export type Bb91 = number;
export type Obp1 = number;
export type Rc1 = number;
export type Babip1 = number;
export type Ra1 = number;
export type Ra91 = number;
export type Oppba1 = number;
export type Oppab91 = number;
export type Opph1 = number;
export type Opph91 = number;
export type Opphr1 = number;
export type Opphr91 = number;
export type Oppabhr1 = number;
export type Oppk1 = number;
export type Oppk91 = number;
export type Oppbb1 = number;
export type Oppbb91 = number;
export type Whip1 = number;
export type Lob1 = number;
export type E1 = number;
export type Fip1 = number;
export type Rd1 = number;
export type Rd91 = number;
export type InningsPlayed1 = number;
export type InningsGame1 = number;
export type Wins1 = number;
export type Losses1 = number;
export type WinsByRunRule1 = number;
export type LossesByRunRule1 = number;
export type Seasons1 = number[];
export type Player5 = string;
export type Team2 = string;
export type Player6 = string;
export type Rs2 = number;
export type Rs92 = number;
export type Ba2 = number;
export type Ab2 = number;
export type Ab92 = number;
export type H2 = number;
export type H92 = number;
export type Hr2 = number;
export type Hr92 = number;
export type Abhr2 = number;
export type So2 = number;
export type So92 = number;
export type Bb2 = number;
export type Bb92 = number;
export type Obp2 = number;
export type Rc2 = number;
export type Babip2 = number;
export type Ra2 = number;
export type Ra92 = number;
export type Oppba2 = number;
export type Oppab92 = number;
export type Opph2 = number;
export type Opph92 = number;
export type Opphr2 = number;
export type Opphr92 = number;
export type Oppabhr2 = number;
export type Oppk2 = number;
export type Oppk92 = number;
export type Oppbb2 = number;
export type Oppbb92 = number;
export type Whip2 = number;
export type Lob2 = number;
export type E2 = number;
export type Fip2 = number;
export type Rd2 = number;
export type Rd92 = number;
export type InningsPlayed2 = number;
export type InningsGame2 = number;
export type Wins2 = number;
export type Losses2 = number;
export type WinsByRunRule2 = number;
export type LossesByRunRule2 = number;
export type Seasons2 = number[];
export type Appearances = number;
export type SeriesWins = number;
export type SeriesLosses = number;
export type ChampionshipSeasons = number[];
export type SecondPlaceSeasons = number[];
export type PlayoffsHeadToHead = HeadToHead[];

/**
 * all-time stats for all players
 */
export interface CareerStats {
  all_players: AllPlayers;
  active_players: ActivePlayers;
  season_performances: SeasonPerformances;
  season_head_to_head: SeasonHeadToHead;
  playoffs_performances: PlayoffsPerformances;
  playoffs_head_to_head: PlayoffsHeadToHead;
  [k: string]: unknown;
}
export interface AllPlayers {
  [k: string]: Player;
}
/**
 * someone who played in XBL
 */
export interface Player {
  player: Player1;
  teams: Teams;
  [k: string]: unknown;
}
/**
 * pairing between a person and a season in XBL
 */
export interface TeamSeason {
  team_name: TeamName;
  team_abbrev: TeamAbbrev;
  league: League;
  season: Season;
  [k: string]: unknown;
}
export interface ActivePlayers {
  [k: string]: string[];
}
export interface SeasonPerformances {
  [k: string]: CareerSeasonPerformance;
}
/**
 * how someone has performed in the regular season over their career
 */
export interface CareerSeasonPerformance {
  player: Player2;
  by_league: ByLeague;
  all_time: CareerSeasonStats;
  [k: string]: unknown;
}
export interface ByLeague {
  [k: string]: CareerSeasonStats;
}
/**
 * high-level wins, losses for a player over their career
 */
export interface CareerSeasonStats {
  team: Team;
  player: Player3;
  rs: Rs;
  rs9: Rs9;
  ba: Ba;
  ab: Ab;
  ab9: Ab9;
  h: H;
  h9: H9;
  hr: Hr;
  hr9: Hr9;
  abhr: Abhr;
  so: So;
  so9: So9;
  bb: Bb;
  bb9: Bb9;
  obp: Obp;
  rc: Rc;
  babip: Babip;
  ra: Ra;
  ra9: Ra9;
  oppba: Oppba;
  oppab9: Oppab9;
  opph: Opph;
  opph9: Opph9;
  opphr: Opphr;
  opphr9: Opphr9;
  oppabhr: Oppabhr;
  oppk: Oppk;
  oppk9: Oppk9;
  oppbb: Oppbb;
  oppbb9: Oppbb9;
  whip: Whip;
  lob: Lob;
  e: E;
  fip: Fip;
  rd: Rd;
  rd9: Rd9;
  innings_played: InningsPlayed;
  innings_game: InningsGame;
  wins: Wins;
  losses: Losses;
  wins_by_run_rule: WinsByRunRule;
  losses_by_run_rule: LossesByRunRule;
  seasons: Seasons;
  sweeps_w: SweepsW;
  sweeps_l: SweepsL;
  splits: Splits;
  [k: string]: unknown;
}
export interface SeasonHeadToHead {
  [k: string]: {
    [k: string]: HeadToHead;
  };
}
/**
 * player_a and player_z must be in alphabetical order
 */
export interface HeadToHead {
  player_a: PlayerA;
  player_z: PlayerZ;
  player_a_stats: TeamStats;
  player_z_stats: TeamStats;
  [k: string]: unknown;
}
/**
 * Performance stats for a team for a given season/playoffs
 */
export interface TeamStats {
  team: Team1;
  player: Player4;
  rs: Rs1;
  rs9: Rs91;
  ba: Ba1;
  ab: Ab1;
  ab9: Ab91;
  h: H1;
  h9: H91;
  hr: Hr1;
  hr9: Hr91;
  abhr: Abhr1;
  so: So1;
  so9: So91;
  bb: Bb1;
  bb9: Bb91;
  obp: Obp1;
  rc: Rc1;
  babip: Babip1;
  ra: Ra1;
  ra9: Ra91;
  oppba: Oppba1;
  oppab9: Oppab91;
  opph: Opph1;
  opph9: Opph91;
  opphr: Opphr1;
  opphr9: Opphr91;
  oppabhr: Oppabhr1;
  oppk: Oppk1;
  oppk9: Oppk91;
  oppbb: Oppbb1;
  oppbb9: Oppbb91;
  whip: Whip1;
  lob: Lob1;
  e: E1;
  fip: Fip1;
  rd: Rd1;
  rd9: Rd91;
  innings_played: InningsPlayed1;
  innings_game: InningsGame1;
  wins: Wins1;
  losses: Losses1;
  wins_by_run_rule: WinsByRunRule1;
  losses_by_run_rule: LossesByRunRule1;
  seasons: Seasons1;
  [k: string]: unknown;
}
export interface PlayoffsPerformances {
  [k: string]: CareerPlayoffsPerformance;
}
/**
 * how someone has performed in the playoffs over their career
 */
export interface CareerPlayoffsPerformance {
  player: Player5;
  by_league: ByLeague1;
  all_time: CareerPlayoffsStats;
  [k: string]: unknown;
}
export interface ByLeague1 {
  [k: string]: CareerPlayoffsStats;
}
/**
 * how someone has performed in the playoffs over their career
 */
export interface CareerPlayoffsStats {
  team: Team2;
  player: Player6;
  rs: Rs2;
  rs9: Rs92;
  ba: Ba2;
  ab: Ab2;
  ab9: Ab92;
  h: H2;
  h9: H92;
  hr: Hr2;
  hr9: Hr92;
  abhr: Abhr2;
  so: So2;
  so9: So92;
  bb: Bb2;
  bb9: Bb92;
  obp: Obp2;
  rc: Rc2;
  babip: Babip2;
  ra: Ra2;
  ra9: Ra92;
  oppba: Oppba2;
  oppab9: Oppab92;
  opph: Opph2;
  opph9: Opph92;
  opphr: Opphr2;
  opphr9: Opphr92;
  oppabhr: Oppabhr2;
  oppk: Oppk2;
  oppk9: Oppk92;
  oppbb: Oppbb2;
  oppbb9: Oppbb92;
  whip: Whip2;
  lob: Lob2;
  e: E2;
  fip: Fip2;
  rd: Rd2;
  rd9: Rd92;
  innings_played: InningsPlayed2;
  innings_game: InningsGame2;
  wins: Wins2;
  losses: Losses2;
  wins_by_run_rule: WinsByRunRule2;
  losses_by_run_rule: LossesByRunRule2;
  seasons: Seasons2;
  appearances: Appearances;
  series_wins: SeriesWins;
  series_losses: SeriesLosses;
  championship_seasons: ChampionshipSeasons;
  second_place_seasons: SecondPlaceSeasons;
  [k: string]: unknown;
}
