name: Build
on:
  # any time we push
  push:
    branches:
      - '**'

jobs:
  checkout-repo:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
  build:
    uses: ./.github/workflows/build.yml
